<?php

namespace app\controllers;

use app\models\forms\BaseForm;
use Yii;
use yii\web\View;
use yii\web\Controller;
use app\models\forms\LoginForm;
use app\models\forms\WriteUsForm;
use yii\helpers\Url;
use app\models\Requests;
use yii\helpers\Html;
use yii\web\Response;
use yii\widgets\ActiveForm;
use app\components\Cache;

class SiteController extends Controller {

    use Cache;
//    public function behaviors() {
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['logout'],
//                'rules' => [
//                    [
//                        'actions' => ['admin'],
//                        'allow' => true,
//                        'roles' => ['admin'],
//                    ],
//                ],
//            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
//        ];
//    }

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->myInit();
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->loginAdmin()) {
            return Yii::$app->getResponse()->redirect(Url::toRoute(['/admin']));
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionIndex() {
        $form = new BaseForm();

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $validate = ActiveForm::validate($form);
            if ($validate) {
                ///Консультация мастера
                $adviceName = Yii::$app->request->post('adviceName');
                $advicePhone = Yii::$app->request->post('advicePhone');

                if ($advicePhone && $adviceName) {
                    $status = false;
                    $request = new Requests();
                    $request->name = $adviceName;
                    $request->phone = $advicePhone;
                    $request->type_id = Requests::ADVICE_ID;
                    $request->save();

                    $status = Yii::$app->mailer->compose()
                        ->setFrom(Yii::$app->system->get('email'))
                        ->setTo(Yii::$app->system->get('email'))
                        ->setSubject('Заявка на консультацию мастера')
                        ->setHtmlBody('Заявка на консультацию мастера.<br>Имя: ' . $adviceName .'<br>Телефон: ' . $advicePhone)
                        ->send();

                    return [
                        'status' => $status,
                    ];
                }

                //Обратный звонок
                $callPhone = Yii::$app->request->post('callPhone');
                $callPhone = trim(Html::encode($callPhone));

                if ($callPhone) {
                    $status = false;
                    $request = new Requests();
                    $request->phone = $callPhone;
                    $request->type_id = Requests::CALLBACK_ID;
                    $request->save();

                    $status = Yii::$app->mailer->compose()
                        ->setFrom(Yii::$app->system->get('email'))
                        ->setTo(Yii::$app->system->get('email'))
                        ->setSubject('Заявка на обратный звонок')
                        ->setTextBody('Нужно перезвонить по номеру: ' . $callPhone)
                        ->send();

                    return [
                        'status' => $status,
                    ];
                }

                //Дисконтная карта
                $cardMail = Yii::$app->request->post('cardMail');
                $cardMail = trim(Html::encode($cardMail));

                if ($cardMail) {
                    $status = false;
                    $request = new Requests();
                    $request->email = $cardMail;
                    $request->type_id = Requests::CARD_ID;
                    $request->save();

                    $status = Yii::$app->mailer->compose()
                        ->setFrom(Yii::$app->system->get('email'))
                        ->setTo(Yii::$app->system->get('email'))
                        ->setSubject('Получение дисконтной карты')
                        ->setHtmlBody('Заявка на получение дисконтной карты от: ' . $cardMail)
                        ->send();

                    $homeUrl = Yii::$app->params['params']['host'];
                    $adminEmail = Yii::$app->system->get('email');
                    $adminPhone = Yii::$app->system->get('phone');
                    $adminSkype = Yii::$app->system->get('skype');

                    $status = Yii::$app->mailer->compose('discount', [
                        'homeUrl' => $homeUrl,
                        'adminEmail' => $adminEmail,
                        'adminPhone' => $adminPhone,
                        'adminSkype' => $adminSkype,
                    ])
                        ->setFrom(Yii::$app->system->get('email'))
                        ->setTo($cardMail)
                        ->setSubject('Получить дисконтную карту')
                        ->attach('files/Blank_discount_card.docx')
                        ->send();

                    return [
                        'status' => $status,
                    ];
                }

                //Вызвать мастера
                $masterName = Yii::$app->request->post('masterName');
                $masterPhone = Yii::$app->request->post('masterPhone');
                $masterName = trim(Html::encode($masterName));
                $masterPhone = trim(Html::encode($masterPhone));

                if ($masterName) {
                    $status = false;
                    $request = new Requests();
                    $request->name = $masterName;
                    $request->phone = $masterPhone;
                    $request->type_id = Requests::MASTER_ID;
                    $request->save();

                    $status = Yii::$app->mailer->compose()
                        ->setFrom(Yii::$app->system->get('email'))
                        ->setTo(Yii::$app->system->get('email'))
                        ->setSubject('Выезд мастера')
                        ->setHtmlBody('Заявка на вызов мастера.<br>Имя: ' . $masterName .'<br>Телефон: ' . $masterPhone)
                        ->send();

                    return [
                        'status' => $status,
                    ];
                }
            }


        }
        return $this->render('index', [
            'letter' => $form
        ]);
    }

    public function actionContacts() {
        $this->view->registerJsFile('/js/map.js?r1', ['position' => View::POS_HEAD]);
        $form = new WriteUsForm();

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $validate = ActiveForm::validate($form);
            if ($validate) {
                $writeName = trim(Html::encode(Yii::$app->request->post('writeUsName')));
                $writePhone = trim(Html::encode(Yii::$app->request->post('writeUsPhone')));
                $writeEmail = trim(Html::encode(Yii::$app->request->post('writeUsEmail')));
                $writeMessage = trim(Html::encode(Yii::$app->request->post('writeUsMessage')));

                $request = new Requests();
                $request->name = $writeName;
                $request->phone = $writePhone;
                $request->email = $writeEmail;
                $request->text = $writeMessage;
                $request->type_id = Requests::WRITE_ID;
                $request->save();

                $validate = Yii::$app->mailer->compose()
                    ->setFrom($writeEmail)
                    ->setTo(Yii::$app->system->get('email'))
                    ->setSubject('Сообщение со страницы "Контакты"')
                    ->setHtmlBody('Имя: ' . $writeName . '<br>Телефон: ' . $writePhone . '<br>Email: ' . $writeEmail . '<br>Сообщение: ' . $writeMessage)
                    ->send();

                return [
                    'status' => $validate
                ];
            }
        }

        return $this->render('contacts', [
            'write' => $form
        ]);
    }

    public function actionRates() {
        return $this->render('rates', [
//            'write' => $form
        ]);
    }

    public function actionFlat() {
        $form = new BaseForm();

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $validate = ActiveForm::validate($form);
            if ($validate) {
                $status = false;
                $request = new Requests();

                $questionName = trim(Html::encode(Yii::$app->request->post('questionName')));
                $questionPhone = trim(Html::encode(Yii::$app->request->post('questionPhone')));
                $questionText = trim(Html::encode(Yii::$app->request->post('questionText')));

                $request->name = $questionName;
                $request->phone = $questionPhone;
                $request->text = $questionText;
                $request->type_id = Requests::QUESTION_ID;
                $request->save();

                $status = Yii::$app->mailer->compose()
                    ->setFrom(Yii::$app->system->get('email'))
                    ->setTo(Yii::$app->system->get('email'))
                    ->setSubject('Вопрос мастеру')
                    ->setHtmlBody('Вопрос мастеру.<br><b>Имя:</b> ' . $questionName .'<br><b>Телефон:</b> ' . $questionPhone . '<br><b>Вопрос:</b> ' . $questionText)
                    ->send();

                return [
                    'status' => $status,
                ];
            }
        }

        return $this->render('flat', [
            'question' => $form
        ]);
    }

    public function actionHouse() {
        $form = new BaseForm();

        return $this->render('house', [
            'question' => $form
        ]);
    }

    public function actionCompany() {
        $form = new BaseForm();

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $validate = ActiveForm::validate($form);
            if ($validate) {
                $status = false;
                $request = new Requests();

                $questionName = trim(Html::encode($form->name));
                $questionPhone = trim(Html::encode($form->phone));
                $questionText = trim(Html::encode($form->text));

                $request->name = $questionName;
                $request->phone = $questionPhone;
                $request->text = $questionText;
                $request->type_id = Requests::QUESTION_ID;
                $request->save();

                $status = Yii::$app->mailer->compose()
                    ->setFrom(Yii::$app->system->get('email'))
                    ->setTo(Yii::$app->system->get('email'))
                    ->setSubject('Вопрос мастеру')
                    ->setHtmlBody('Вопрос мастеру.<br><b>Имя:</b> ' . $questionName .'<br><b>Телефон:</b> ' . $questionPhone . '<br><b>Вопрос:</b> ' . $questionText)
                    ->send();

                return [
                    'status' => $status,
                ];
            }
        }

        return $this->render('company', [
            'question' => $form
        ]);
    }

    public function actionPrivacyPolicy() {
        return $this->render('privacy-policy');
    }

}
