<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Works;
use app\models\WorksCat;
use yii\data\Pagination;
use app\models\WorksSlides;
use yii\helpers\Url;
use yii\web\HttpException;
use app\components\Cache;

class WorksController extends Controller {

    use Cache;

    const PAGE_SIZE = 9;

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->myInit();
    }

    public function actionIndex() {
        $works = new Works();
        $worksCat = new WorksCat();
        $query = $works->getAllCat(['works.active' => 1], '(case when works.sort = 0 then 1 else 0 end), works.sort, works.id DESC', false);

        $group = Yii::$app->request->getQueryParam('group') ? Yii::$app->request->getQueryParam('group') : false;
        $items = $works->filter($query, []);

        switch ($group) {
            case 'all';
                $items = $works->filter($query, []);
                break;
            case 'house';
                $cat = $worksCat->findOne(['key' => 'house']);
                if (!empty($cat)) {
                    $items = $works->filter($query, ['works.cat_id' => $cat->id, 'works.active' => 1]);
                }
                break;
            case 'flat';
                $cat = $worksCat->findOne(['key' => 'flat']);
                if (!empty($cat)) {
                    $items = $works->filter($query, ['works.cat_id' => $cat->id, 'works.active' => 1]);
                }
                break;
        }

        $pager = new Pagination(['totalCount' => $items->count(), 'pageSize' => self::PAGE_SIZE]);
        $pager->pageSizeParam = false;

        $works = $items->offset($pager->offset)
            ->limit($pager->limit)
            ->all();

        return $this->render('index', [
            'works' => $works,
            'pager' => $pager,
        ]);
    }

    public function actionSingle() {
        $this->view->registerCssFile('/lib/PgwSlider/pgwslider.min.css');
        $this->view->registerCssFile('/lib/Prokrutka/jquery.mCustomScrollbar.css');
        $this->view->registerJsFile('/lib/Prokrutka/jquery.mCustomScrollbar.concat.min.js');
        $this->view->registerJsFile('/lib/PgwSlider/pgwslider.min.js');

        $id = !empty(Yii::$app->request->getQueryParam('id')) ? Yii::$app->request->getQueryParam('id') : false;

        if ($id) {
            $work = Works::findOne(['id' => $id, 'active' => 1]);
            if (!$work) {
                throw new HttpException(404 ,'Такой страницы нет!');
            }
            $images = WorksSlides::findAll(['work_id' => $id]);

            if ($work['sort'] > 0) {
                $prev = Works::find()->where('((sort = ' . $work['sort'] . ') AND id > ' . $id . ') OR (sort < ' . $work['sort'] . ') AND id != ' . $id . ' AND active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), `sort` DESC, id')->limit(1)->one();
                $prev = !is_null($prev) ? $prev->id : Works::find()->where('(sort >= ' . $work['sort'] . ') AND id != ' . $id . ' AND active = 1')->orderBy('sort DESC, id DESC')->limit(1)->one()->id;
                $next = Works::find()->where('((sort = ' . $work['sort'] . ') AND id < ' . $id . ') OR (sort > ' . $work['sort'] . ') AND id != ' . $id . ' AND active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), `sort`, id DESC')->limit(1)->one();
                $next = !is_null($next) ? $next->id : Works::find()->where('(sort <= ' . $work['sort'] . ') AND id != ' . $id . ' AND active = 1')->orderBy('sort, id DESC')->limit(1)->one()->id;
            }
            if ($work['sort'] == 0) {
                $prev = Works::find()->where('sort = 0 AND id > ' . $id . ' AND active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), `sort`, id')->limit(1)->one();
                $prev = !is_null($prev) ? $prev->id : Works::find()->where('(sort >= ' . $work['sort'] . ') AND id != ' . $id . ' AND active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), sort DESC, id DESC')->limit(1)->one()->id;
                $next = Works::find()->where('sort = 0 AND id < ' . $id . ' AND active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), `sort`, id DESC')->limit(1)->one();
                $next = !is_null($next) ? $next->id : Works::find()->where('(sort >= ' . $work['sort'] . ') AND id != ' . $id . ' AND active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), sort, id DESC')->limit(1)->one()->id;
            }

            $other = Works::find()->where('active = 1')->orderBy('(case when sort = 0 then 1 else 0 end), sort ASC, id DESC');
            $pager = new Pagination(['totalCount' => $other->count(), 'pageSize' => 3]);
            $pager->pageSizeParam = false;
            $other = $other->offset($pager->offset)
                ->limit($pager->limit)
                ->all();
        } else {
            Yii::$app->getResponse()->redirect(Url::toRoute('works/'));
            return false;
        }

        return $this->render('single', [
            'work' => $work,
            'images' => $images,
            'prev' => $prev,
            'next' => $next,
            'other' => $other,
            'pager' => $pager
        ]);
    }

    public function actionVideo() {
        $videos = Works::find()->where('active = 1 AND video IS NOT NULL')->orderBy(['id' => SORT_DESC]);
        $pager = new Pagination(['totalCount' => $videos->count(), 'pageSize' => self::PAGE_SIZE]);
        $pager->pageSizeParam = false;

        $videos = $videos->offset($pager->offset)
            ->limit($pager->limit)
            ->all();

        return $this->render('video', [
            'videos' => $videos,
            'pager' => $pager
        ]);
    }

}